version: "0.0.1"

services:
  storage:
    image: redis:latest
    volumes:
      - ./data:/data

  counter:
#    image: segacho/bookcounter:0.0.1
    build: ./counter
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    ports:
      - 8100:3003
    depends_on:
      - storage

  bookshelf:
    image: segacho/bookshelf:latest
    environment:
      - PORT=3003
      - COUNTER_URL=http://counter
      - COUNTER_PORT=3003
      - MONGO_DB_URL=mongodb://root:example@mongo:27017/
    ports:
      - 8000:3003
    depends_on:
      - counter

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false