version: "0.0.1"

services:
  storage:
    image: redis:latest
    volumes:
      - ./data:/data

  counter:
#    image: segacho/bookcounter:0.0.1
    build: ./counter
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    ports:
      - 8100:3003
    depends_on:
      - storage

  bookshelf:
    image: segacho/bookshelf:latest
    environment:
      - PORT=3003
      - COUNTER_URL=http://counter
      - COUNTER_PORT=3003
    ports:
      - 8000:3003
    depends_on:
      - counter
